
  <?php do_action('dynamicnews_before_footer'); ?>

  <!--  All the code below (except the outermost two divs) was generated by Contact Form 7
        In order to place this email sign up bar directly into the footer, I obtained 
        the raw HTML generated by the Contact Form 7 "shortcode" by placing it into a 
        page, visiting that page, viewing the source code and then copy and pasting the
        raw HTML code here 

        Form Name = "Simple Email-Only Sign Up"
  -->
  <div class="simple-email-form-container">
    <div class="simple-email-form-content">
      <div role="form" class="wpcf7" id="wpcf7-f97-p6-o1" lang="en-US" dir="ltr">
        <div class="screen-reader-response"></div>
        <form name="simple-email-form-footer" action="/#wpcf7-f97-p6-o1" method="post" class="wpcf7-form" novalidate="novalidate">
          <div style="display: none;">
            <input type="hidden" name="_wpcf7" value="97" />
            <input type="hidden" name="_wpcf7_version" value="4.2.1" />
            <input type="hidden" name="_wpcf7_locale" value="en_US" />
            <input type="hidden" name="_wpcf7_unit_tag" value="wpcf7-f97-p6-o1" />
            <input type="hidden" name="_wpnonce" value="1866e611f2" />
          </div>
          <p>
            <span class="wpcf7-form-control-wrap your-email">
              <input type="email" name="your-email" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-email wpcf7-validates-as-required wpcf7-validates-as-email simple-email-form-submit" aria-required="true" aria-invalid="false" placeholder="Enter your email to receive updates from us" />
            </span> 
            <input type="submit" value="Sign Up" class="wpcf7-form-control wpcf7-submit simple-email-form-submit" />
          </p>
          <div class="wpcf7-response-output wpcf7-display-none"></div>
        </form>
      </div>
    </div> 
  </div>
 

  <div id="footer-wrap">
  
    <footer id="footer" class="container clearfix" role="contentinfo">

      <div class="footer-container">

        <!-- Links block 1 -->
        <div class="footer-col first-footer-col">
          <a href="/"><p class="footer-title title menu-title">Home</p></a>
          <a href="/get-quote"><p class="footer-title title menu-title">Get Quote</p></a>
          <a href="/available-policies"><p class="footer-title title menu-title">Available Policies</p></a>
            <a href="/auto-insurance"><p class="footer-text">Auto Insurance</p></a>
            <a href="/homeowners-insurance"><p class="footer-text">Homeowners Insurance</p></a>
            <a href="/life-insurance"><p class="footer-text">Life Insurance</p></a>
            <a href="/renters-insurance"><p class="footer-text">Renters Insurance</p></a>
            <a href="/motorcycle-insurance"><p class="footer-text">Motorcycle Insurance</p></a>
            <a href="/umbrella-insurance"><p class="footer-text">Umbrella Insurance</p></a>
            <a href="/rewards-program"><p class="footer-title title menu-title">Rewards Program</p></a>
        </div>

        <!-- Links block 2 -->
        <div class="footer-col stacked-cols-right">
          <a href="/community-support"><p class="footer-title title menu-title">Community Support</p></a>
            <a href="/community-support/our-causes"><p class="footer-text">Our Community Causes</p></a>
            <a href="/community-support/nominate-a-cause"><p class="footer-text">Nominate A Cause</p></a>
          <a href="/about-us"><p class="footer-title title menu-title">About Us</p></a>
            <a href="/about-us#DavidMcBrayer"><p class="footer-text">David McBrayer</p></a>
            <a href="/about-us#AdamMcBrayer"><p class="footer-text">Adam McBrayer</p></a>
            <a href="/about-us#SandyMcBrayer"><p class="footer-text">Sandy McBrayer</p></a>
            <a href="/about-us#TurnerMay"><p class="footer-text">Turner May</p></a>
          <a href="/blog"><p class="footer-title title menu-title">Blog</p></a>
        </div>
       
       <!-- Contact block -->
        <div class="footer-col contact-col">
          <p class="footer-title title">Contact Us<p>
          <div class="footer-col-row">
            <p class="footer-text">The McBrayer Agency</p>
          </div>
          <div class="footer-col-row">
            <p class="footer-text">(205) 304-0414</p>
            <p class="footer-text">(205) 594-6275 fax</p>
            <p class="footer-text small-email-text">info@themcbrayeragency.com</p>
          </div>
          <div class="footer-col-row">
            <p class="footer-text">122 1st Street S.</p>
            <p class="footer-text">Alabaster, AL 35007</p>
          </div>
          <div class="contact-col-button">
            <a href="https://www.google.com/maps/dir/Current+Location/122+1st+St+S,+Alabaster,+AL+35007" target='_blank' class="contact-button-link">
              <p class="contact-button-link">Get Directions</p>
            </a>
          </div>
          <div class="contact-col-button">
            <a href="tel:+2053040414" class="contact-button-link">
              <p class="contact-button-link">Call Now</p>
            </a>
          </div>
        </div>


        
        <!-- Logo, Search and Social Icons column -->
        <div class="footer-col far-right-footer-col stacked-cols-right">

          <!-- Logo with blue BG -->
          <img src="<?php echo get_stylesheet_directory_uri(); ?>/images/logo-blue-bg.png" alt="McBrayer Insurance Agency Logo" class="footer-logo"/>

          <!-- Social Icons -->
          <div class="footer-social-icons social-icons-wrap clearfix">
            <?php dynamicnews_display_social_icons(); ?>
          </div>

          <!-- Search Bar -->
          <div class="footer-search-bar">
            <form role="search" method="get" class="search-form" action="<?php echo esc_url( home_url( '/' ) ); ?>">
              <label>
                <span class="screen-reader-text"><?php _ex( 'Search for:', 'label', 'dynamicnewslite' ); ?></span>
                  <input type="search" class="search-field" placeholder="<?php echo esc_attr_x( 'Search &hellip;', 'placeholder', 'dynamicnewslite' ); ?>" value="<?php echo esc_attr( get_search_query() ); ?>" name="s" />
              </label>
              <button type="submit" class="search-submit">
                <span class="genericon-search"></span>
              </button>
            </form>
          </div>
        </div>
      </div> <!-- End of footer container div -->
    </footer>    
  </div>
</div><!-- end #wrapper -->

<?php wp_footer(); ?>
</body>
</html>