<section id="sidebar" class="secondary clearfix"><!-- This section tag had role="complementary" but HTML validator complained -->

  <!-- Click Here for $10 button -->
  <a href="/rewards-program" class="click-for-10-link-div">
    <div class="click-for-10-button">
      <p class="title">Click Here for $10</p>
    </div>
  </a>

  <!-- Recent News section (aka: recent posts) -->
  <div class="widget-box">
    <div class="widget-title title">
      <p><?php _e("Recent News"); ?></p>
    </div>
    <div class="widget-contents">
      <ul>
        <?php
          $recent_posts = wp_get_recent_posts(array('numberposts' => '8', 'post_status' => 'publish'));
          foreach( $recent_posts as $recent ) {
            echo '<li class="recent-items"><a href="' . esc_url(get_permalink($recent['ID'])) . '" title="Look '.esc_attr($recent['post_title']).'" >' . $recent['post_title'] . '</a></li>';
          }
        ?>
      </ul>
    </div>
  </div>

  <!-- Get A Quote Form -->
  <div class="widget-box get-quote-widget-box">
    <div class="widget-title title">
      <p>Get A Quote</p>
    </div>
    <div class="widget-contents get-quote-widget">
      <!--  All the code below (except the outermost two divs) was generated by Contact Form 7
      In order to place this email sign up bar directly into the footer, I obtained 
      the raw HTML generated by the Contact Form 7 "shortcode" by placing it into a 
      page, visiting that page, viewing the source code and then copy and pasting the
      raw HTML code here 

      Form Name = "Simple Get Quote Form"
      -->

      <div class="widget-contents get-quote-widget">
        <div role="form" class="wpcf7" id="wpcf7-f98-p48-o1" lang="en-US" dir="ltr">
          <div class="screen-reader-response"></div>
          <form name="get-quote-sidebar" action="/get-quote#wpcf7-f98-p48-o1" method="post" class="wpcf7-form" novalidate="novalidate">
            <div style="display: none;">
              <input type="hidden" name="_wpcf7" value="98" />
              <input type="hidden" name="_wpcf7_version" value="4.2.1" />
              <input type="hidden" name="_wpcf7_locale" value="en_US" />
              <input type="hidden" name="_wpcf7_unit_tag" value="wpcf7-f98-p48-o1" />
              <input type="hidden" name="_wpnonce" value="7596dc5b43" />
            </div>
          
            <div class="get-quote-sidebar-form-row">
              <p><span class="wpcf7-form-control-wrap your-name"><input type="text" name="your-name" value="" size="40" class="wpcf7-form-control wpcf7-text sidebar-get-quote-input" aria-invalid="false" placeholder="Your Name" /></span></p>
            </div>

            <div class="get-quote-sidebar-form-row">
              <p><span class="wpcf7-form-control-wrap your-email"><input type="email" name="your-email" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-email sidebar-get-quote-input" aria-invalid="false" placeholder="Your Email" /></span></p>
            </div>

            <div class="get-quote-sidebar-form-row">
              <p><span class="wpcf7-form-control-wrap your-telephone"><input type="tel" name="your-telephone" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-tel wpcf7-validates-as-required wpcf7-validates-as-tel sidebar-get-quote-input" aria-required="true" aria-invalid="false" placeholder="Your Telephone" /></span></p>
            </div>
          
            <div class="get-quote-sidebar-form-row">
              <!-- This custom div enables styling of select options -->
              <div class="get-quote-policy-select">
                <span class="wpcf7-form-control-wrap Policies"><select name="Policies" 
                class="wpcf7-form-control wpcf7-select wpcf7-validates-as-required policies-dropdown sidebar-get-quote-input" aria-required="true" aria-invalid="false"><option value="Policy Type">Policy Type</option><option value="Auto Insurance">Auto Insurance</option><option value="Homeowners Insurance">Homeowners Insurance</option><option value="Renters Insurance">Renters Insurance</option><option value="Motorcycle Insurance">Motorcycle Insurance</option><option value="Boat Insurance">Boat Insurance</option><option value="Life Insurance">Life Insurance</option><option value="Umbrella Insurance">Umbrella Insurance</option></select></span>
              </div>
            </div>
          
            <div class="get-quote-sidebar-form-row">
              <p><span class="wpcf7-form-control-wrap your-message"><textarea name="your-message" cols="40" rows="10" class="wpcf7-form-control wpcf7-textarea sidebar-get-quote-input" aria-invalid="false" placeholder="Questions or Comments"></textarea></span></p>
            </div>
            
            <p><input type="submit" value="Get a Quote" class="wpcf7-form-control wpcf7-submit get-quote-sidebar-form-submit" /></p>

            <div class="wpcf7-response-output wpcf7-display-none"></div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>